### ISSUE TITLE
File not saving correctly

### ISSUE THREAD

**Issue by Joly0** [L4stIdi0t/arr-tools#2] opened 2024-07-22 20:17 UTC
Hey, i am not sure what is wrong, but i have setup jellyfin, sonarr and radarr and when i try to use swipearr, i get this error message:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/backend/workers/sonarr.py", line 521, in run
    return main_run(dry)
  File "/app/backend/workers/sonarr.py", line 488, in main_run
    arr_items = sonarr.get_series()
  File "/usr/local/lib/python3.10/site-packages/pyarr/sonarr.py", line 477, in get_series
    return self._get(path, self.ver_uri)
  File "/usr/local/lib/python3.10/site-packages/pyarr/request_handler.py", line 81, in _get
    res = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sonarr', port=8989): Max retries exceeded with url: /api/v3/series (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1509cb986680>: Failed to resolve 'sonarr' ([Errno -2] Name or service not known)"))
```

There are also a bunch of other errors, but i think they might be connected to those errors.

Btw, for the server address i used "http://local-ip:port/" for both radarr and sonarr

**Comment by Joly0** [comment] 2024-07-22 20:20
Oh, and also restarting the container resets all settings.

**Comment by Joly0** [comment] 2024-07-22 20:22
I think setting sonarr resets the media server settings and vice-versa

**Comment by mah-thingies** [comment] 2024-07-22 22:55
i got to be honest i noticed it as well in the latest version on my own setup, but i thought that i messed up as a user and not a bug, ill look into it

the error you are getting is that the adress is http://sonarr:8989/ which is because it is reset

**Comment by mah-thingies** [comment] 2024-07-23 10:58
Well, I cannot find it, and I have tried to reproduce it but have failed.
I will leave it open for now because it may still exist but i believe it is fixed in a previous commit

**Comment by Joly0** [comment] 2024-07-26 09:18
I just repulled the latest image and now getting this error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/app/backend/routers/radarr.py", line 85, in get_info
    quality_profiles = [{k: v for k, v in d.items() if k in ['name', 'id']} for d in radarr.get_quality_profile()]
  File "/usr/local/lib/python3.10/site-packages/pyarr/base.py", line 338, in get_quality_profile
    return self._get(path, self.ver_uri)
  File "/usr/local/lib/python3.10/site-packages/pyarr/request_handler.py", line 81, in _get
    res = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='radarr', port=7878): Max retries exceeded with url: /api/v3/qualityprofile (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x154d22d9ae90>: Failed to resolve 'radarr' ([Errno -2] Name or service not known)"))
```

**Comment by Joly0** [comment] 2024-07-26 09:20
And the settings keep resetting each other. Now it isnt sonarr anymore, but radarr. When i configure radarr, it resets jellyfin/emby, when i configure emby/jellyfin it resets radarr. This is not visible in the webgui, but in the config file for whatever reason

**Comment by mah-thingies** [comment] 2024-07-26 18:31
Are you sure you are running the latest version? 0.1.3, you can see it on the home page

because this commit should have fixed it
https://github.com/mah-thingies/arr-tools/commit/c1d93b2741ad5eab2a74fc196b21e412d15d12a8

to force the webgui to get the latest data refresh the page because it should pull the data

**Comment by Joly0** [comment] 2024-07-26 22:01
![grafik](https://github.com/user-attachments/assets/512d80dc-2da4-479a-baad-b1a421015f62)
I would say yes, i am running the latest version

**Comment by Joly0** [comment] 2024-07-26 22:07
I reinstalled arr-tools, removed the files in the volume and reconfigured jellyfin, then sonarr, then radarr. Now getting this again:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/app/backend/routers/sonarr.py", line 33, in get_items
    return sonarr.get_series()
  File "/usr/local/lib/python3.10/site-packages/pyarr/sonarr.py", line 477, in get_series
    return self._get(path, self.ver_uri)
  File "/usr/local/lib/python3.10/site-packages/pyarr/request_handler.py", line 81, in _get
    res = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sonarr', port=8989): Max retries exceeded with url: /api/v3/series (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x14f3e78e9a20>: Failed to resolve 'sonarr' ([Errno -2] Name or service not known)"))
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 398, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x14f3f40da440>: Failed to resolve 'sonarr' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='sonarr', port=8989): Max retries exceeded with url: /api/v3/qualityprofile (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x14f3f40da440>: Failed to resolve 'sonarr' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/app/backend/routers/sonarr.py", line 22, in get_info
    quality_profiles = [{k: v for k, v in d.items() if k in ['name', 'id']} for d in sonarr.get_quality_profile()]
  File "/usr/local/lib/python3.10/site-packages/pyarr/base.py", line 338, in get_quality_profile
    return self._get(path, self.ver_uri)
  File "/usr/local/lib/python3.10/site-packages/pyarr/request_handler.py", line 81, in _get
    res = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sonarr', port=8989): Max retries exceeded with url: /api/v3/qualityprofile (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x14f3f40da440>: Failed to resolve 'sonarr' ([Errno -2] Name or service not known)"))
```

**Comment by Joly0** [comment] 2024-07-26 22:08
Also, after restarting the container, all settings are reset, except the ones i set last (in my case radarr)

**Comment by Joly0** [comment] 2024-07-26 22:19
I still can see in the config file "config.json", that when i have my jellyfin configured, i can see the configured values in the file. As soon as i configure sonarr, sonarr is configured in the config file, but the configs for jellyfin are replaced with the default values

**Comment by mah-thingies** [comment] 2024-07-28 21:16
I'll add debugging logs in the next build which will be before the end of the month, if you could post that log when this happens i hope i can solve it because i am not able to recreate this

and also add hot reloading of the config everywhere instead of some things not being supported

**Comment by Joly0** [comment] 2024-08-05 21:23
Hey, any news?

**Comment by L4stIdi0t** [comment] 2024-08-06 08:26
Well, i just published an update, it should be fixed in case it is not fixed please create a file called DEBUG o DEBUG.txt in your /data directory to force debug logging
like this:
![image](https://github.com/user-attachments/assets/ee4b95bb-8e98-4ee3-9b55-8508326d22f4)

in case you are using unraid you might want to update the repo because it has moved,
you can edit your current template or remove it and reinstall it from the community apps section

**Comment by Joly0** [comment] 2024-08-06 15:50
It looks like its working now. Atleast is dont see any error anymore and i see somethign in the swipearr tab

**Comment by L4stIdi0t** [comment] 2024-08-09 09:43
Awesome, feel free to open new issues if they arise(hopefully not)

**Closed as completed by L4stIdi0t** 2024-08-09 09:43 UTC
Labels: bug

**Comment by Joly0** [comment] 2024-08-09 12:20
> Awesome, feel free to open new issues if they arise(hopefully not)

Sure will. Thanks for your support fixing this issue. Much appreciated :)
